apiVersion: v2
name: cluster-manager-server
description: The cluster manager server manages cluster information that to be registered with LLMariner.
home: https://llmariner.ai/
icon: https://raw.githubusercontent.com/llmariner/llmariner.github.io/refs/heads/main/assets/icons/logo.svg
type: application
version: 1.7.0
appVersion: 1.7.0
sources:
  - https://github.com/llmariner/cluster-manager
keywords:
  - llmariner
annotations:
  "artifacthub.io/category": ai-machine-learning
  "artifacthub.io/license": Apache-2.0
