// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package legacy

import (
	context "context"
	v1 "github.com/llmariner/cluster-manager/api/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClustersInternalServiceClient is the client API for ClustersInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClustersInternalServiceClient interface {
	ListInternalClusters(ctx context.Context, in *v1.ListInternalClustersRequest, opts ...grpc.CallOption) (*v1.ListInternalClustersResponse, error)
}

type clustersInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClustersInternalServiceClient(cc grpc.ClientConnInterface) ClustersInternalServiceClient {
	return &clustersInternalServiceClient{cc}
}

func (c *clustersInternalServiceClient) ListInternalClusters(ctx context.Context, in *v1.ListInternalClustersRequest, opts ...grpc.CallOption) (*v1.ListInternalClustersResponse, error) {
	out := new(v1.ListInternalClustersResponse)
	err := c.cc.Invoke(ctx, "/llmoperator.clusters.server.v1.ClustersInternalService/ListInternalClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClustersInternalServiceServer is the server API for ClustersInternalService service.
// All implementations must embed UnimplementedClustersInternalServiceServer
// for forward compatibility
type ClustersInternalServiceServer interface {
	ListInternalClusters(context.Context, *v1.ListInternalClustersRequest) (*v1.ListInternalClustersResponse, error)
	mustEmbedUnimplementedClustersInternalServiceServer()
}

// UnimplementedClustersInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClustersInternalServiceServer struct {
}

func (UnimplementedClustersInternalServiceServer) ListInternalClusters(context.Context, *v1.ListInternalClustersRequest) (*v1.ListInternalClustersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInternalClusters not implemented")
}
func (UnimplementedClustersInternalServiceServer) mustEmbedUnimplementedClustersInternalServiceServer() {
}

// UnsafeClustersInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClustersInternalServiceServer will
// result in compilation errors.
type UnsafeClustersInternalServiceServer interface {
	mustEmbedUnimplementedClustersInternalServiceServer()
}

func RegisterClustersInternalServiceServer(s grpc.ServiceRegistrar, srv ClustersInternalServiceServer) {
	s.RegisterService(&ClustersInternalService_ServiceDesc, srv)
}

func _ClustersInternalService_ListInternalClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListInternalClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersInternalServiceServer).ListInternalClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmoperator.clusters.server.v1.ClustersInternalService/ListInternalClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersInternalServiceServer).ListInternalClusters(ctx, req.(*v1.ListInternalClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClustersInternalService_ServiceDesc is the grpc.ServiceDesc for ClustersInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClustersInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmoperator.clusters.server.v1.ClustersInternalService",
	HandlerType: (*ClustersInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInternalClusters",
			Handler:    _ClustersInternalService_ListInternalClusters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/legacy/cluster_manager_service.proto",
}

// ClustersWorkerServiceClient is the client API for ClustersWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClustersWorkerServiceClient interface {
	// GetSelfCluster returns the cluster to which the worker cluster itself belongs.
	GetSelfCluster(ctx context.Context, in *v1.GetSelfClusterRequest, opts ...grpc.CallOption) (*v1.Cluster, error)
}

type clustersWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClustersWorkerServiceClient(cc grpc.ClientConnInterface) ClustersWorkerServiceClient {
	return &clustersWorkerServiceClient{cc}
}

func (c *clustersWorkerServiceClient) GetSelfCluster(ctx context.Context, in *v1.GetSelfClusterRequest, opts ...grpc.CallOption) (*v1.Cluster, error) {
	out := new(v1.Cluster)
	err := c.cc.Invoke(ctx, "/llmoperator.clusters.server.v1.ClustersWorkerService/GetSelfCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClustersWorkerServiceServer is the server API for ClustersWorkerService service.
// All implementations must embed UnimplementedClustersWorkerServiceServer
// for forward compatibility
type ClustersWorkerServiceServer interface {
	// GetSelfCluster returns the cluster to which the worker cluster itself belongs.
	GetSelfCluster(context.Context, *v1.GetSelfClusterRequest) (*v1.Cluster, error)
	mustEmbedUnimplementedClustersWorkerServiceServer()
}

// UnimplementedClustersWorkerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClustersWorkerServiceServer struct {
}

func (UnimplementedClustersWorkerServiceServer) GetSelfCluster(context.Context, *v1.GetSelfClusterRequest) (*v1.Cluster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSelfCluster not implemented")
}
func (UnimplementedClustersWorkerServiceServer) mustEmbedUnimplementedClustersWorkerServiceServer() {}

// UnsafeClustersWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClustersWorkerServiceServer will
// result in compilation errors.
type UnsafeClustersWorkerServiceServer interface {
	mustEmbedUnimplementedClustersWorkerServiceServer()
}

func RegisterClustersWorkerServiceServer(s grpc.ServiceRegistrar, srv ClustersWorkerServiceServer) {
	s.RegisterService(&ClustersWorkerService_ServiceDesc, srv)
}

func _ClustersWorkerService_GetSelfCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetSelfClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersWorkerServiceServer).GetSelfCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/llmoperator.clusters.server.v1.ClustersWorkerService/GetSelfCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersWorkerServiceServer).GetSelfCluster(ctx, req.(*v1.GetSelfClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClustersWorkerService_ServiceDesc is the grpc.ServiceDesc for ClustersWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClustersWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmoperator.clusters.server.v1.ClustersWorkerService",
	HandlerType: (*ClustersWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSelfCluster",
			Handler:    _ClustersWorkerService_GetSelfCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/legacy/cluster_manager_service.proto",
}
